config/routes.rb
Cmwp::Application.routes.draw do
  resources :users do
    get 'user_cancel', :on => :member
  end
  resources :usrrels
  resources :notices
  resources :custs do
    resources :custloans
    resources :loanreports
  end
  resources :custloans do
    resources :loan_steps do
      get 'add_new', :on => :member
    end
    get 'roll_back', :on => :member
    get 'paymentplan', :on => :member
  end
  resources :loanreports do
    resources :loan_report_steps
    get 'loan_interest', :on => :member
  end
  resources :custrels
  resources :sessions, :only => [:new, :create, :destroy]
  resources :departments, :only => [:index, :show] do
    resources :deptindices do
      get 'dept_index', :on => :member
    end
  end
  resources :branches, :only => [:index, :show] do
    get 'typebrokers', :on => :member
    resources :branchindices do
      get 'branch_index', :on => :member
    end
  end
  resources :brokers, :only => [:index, :show] do
    resources :brokerindices do
      get 'broker_index', :on => :member
    end
    member do
      get :relbrokers
    end
  end
  resources :categories do
    get 'search', :on => :collection
  end
  
  root :to => 'pages#home'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new' 
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'  
  
  match '/todo',    :to => 'pages#todo'  
  
  

end

app/models/custloan.rb
class Custloan < ActiveRecord::Base
  attr_accessible :bank, :bank_contact, :begin_date, :cust_id, :end_date, :guarantee_type, :mobile, 
                  :pawn, :status, :total_amount, :user_id, :current_step, :loanstepones_attributes,
                  :loansteptwos_attributes, :loanstepthrees_attributes, :loanstepfours_attributes,
                  :loanstepfifths_attributes, :loanstepsixths_attributes, :loanstepsevens_attributes,
                  :loanstepeights_attributes, :loanstepnines_attributes, :loansteptens_attributes,
                  :loansteponeguarantees_attributes, :loansteponeassets_attributes,
                  :loanstepfourguarantees_attributes, :loanstepfourassets_attributes,
                  :loansteptwoguarantors_attributes, :loanstepsevenadditionals_attributes,
                  :loanstepeightguarantors_attributes, :loanstepnineadditionals_attributes, :memo,
                  :loanpaymentplans_attributes, :loanpaymentplandetails_attributes
  
  belongs_to :cust
  belongs_to :user
  
  has_many :loanstepones
  has_many :loansteptwos
  has_many :loanstepthrees
  has_many :loanstepfours
  has_many :loanstepfifths
  has_many :loanstepsixths
  has_many :loanstepsevens
  has_many :loanstepeights
  has_many :loanstepnines
  has_many :loansteptens
  has_many :loansteponeguarantees
  has_many :loansteponeassets
  has_many :loanstepfourguarantees
  has_many :loanstepfourassets
  has_many :loansteptwoguarantors
  has_many :loanstepsevenadditionals
  has_many :loanstepeightguarantors
  has_many :loanstepnineadditionals
  has_many :loanpaymentplans
  has_many :loanpaymentplandetails
  
  # validates :total_amount,  :presence => true
  # validates :cust_id,  :presence => true

  accepts_nested_attributes_for :loanstepones
  accepts_nested_attributes_for :loansteptwos#, \
    # :reject_if => proc {|attributes| attributes['filename'].blank? \
    # && attributes['filename_cache'].blank?}
  accepts_nested_attributes_for :loanstepthrees
  accepts_nested_attributes_for :loanstepfours
  accepts_nested_attributes_for :loanstepfifths
  accepts_nested_attributes_for :loanstepsixths
  accepts_nested_attributes_for :loanstepsevens
  accepts_nested_attributes_for :loanstepeights
  accepts_nested_attributes_for :loanstepnines
  accepts_nested_attributes_for :loansteptens
  accepts_nested_attributes_for :loansteponeguarantees
  accepts_nested_attributes_for :loansteponeassets
  accepts_nested_attributes_for :loanstepfourguarantees
  accepts_nested_attributes_for :loanstepfourassets
  accepts_nested_attributes_for :loansteptwoguarantors
  accepts_nested_attributes_for :loanstepsevenadditionals
  accepts_nested_attributes_for :loanstepeightguarantors
  accepts_nested_attributes_for :loanstepnineadditionals
  accepts_nested_attributes_for :loanpaymentplans
  accepts_nested_attributes_for :loanpaymentplandetails
  
  scope :status3, where(:status => Dict.find_by_dict_type_and_code("loanStatus",3))
  scope :status12, where("status <> ?", Dict.find_by_dict_type_and_code("loanStatus",3))
  
  def self.nextstep(id)
    custloan = Custloan.find(id)
    current_step = custloan.current_step
    if current_step >= 1 && current_step < 10
      current_step+1
    end
  end
  
  def self.prevstep(id)
    custloan = Custloan.find(id)
    current_step = custloan.current_step
    if current_step <= 10 && current_step > 1
      current_step-1
    end
  end
end
# == Schema Information
#
# Table name: custloans
#
#  id             :integer         not null, primary key
#  cust_id        :integer
#  status         :integer
#  user_id        :integer
#  total_amount   :float
#  guarantee_type :integer
#  begin_date     :datetime
#  end_date       :datetime
#  pawn           :string(255)
#  bank           :integer
#  bank_contact   :string(255)
#  mobile         :string(255)
#  created_at     :datetime        not null
#  updated_at     :datetime        not null
#  current_step   :integer
#  memo           :string(255)
#  serv_user_id   :integer
#

app/controllers/custloans_controller.rb
# encoding: utf-8
class CustloansController < ApplicationController
  # include Wicked::Wizard
  # steps :one, :two, :three, :four, :five, :six, :seven, :eight, :nine, :ten
  
  before_filter :authenticate, :only => [:index, :show, :edit, :update, :destroy]
  
  def index
    if User.manager?(current_user)
      @custloans = Custloan.status12.order("updated_at DESC").paginate(:page => params[:page]).per_page(20)
    else
      @custloans = ownloans(current_user).sort_by{ |m| m.updated_at }.reverse!
    end
    @title = "信贷记录"
  end  
  
  def show
    @custloan = Custloan.find(params[:id])
    @custloan.loansteptwos.build
    @cust = Cust.find(@custloan.cust_id)
    @title = "信贷记录"
    current_step = @custloan.current_step
    case current_step
    when 1
      @next_step = 'two'
    when 2
      @next_step = 'three'
      @prev_step = 'one'
    when 3
      @next_step = 'four'
      @prev_step = 'three'
    when 4
      @next_step = 'five'
      @prev_step = 'three'
    when 5
      @next_step = 'six'
      @prev_step = 'five'
    when 6
      @next_step = 'seven'
      @prev_step = 'six'
    when 7
      @next_step = 'eight'
      @prev_step = 'seven'
    when 8
      @next_step = 'nine'
      @prev_step = 'eight'
    when 9
      @next_step = 'ten'
      @prev_step = 'nine'
    when 10
      @next_step = 'ten'
      @current_step = 'ten'
    end
  end
  
  def new
    @custloan = Custloan.new
    @custloan.loanstepones.build
    @cust = Cust.find_by_id(params[:cust_id])
    @title = "1 初步可行性"
    @banks = get_dict_by_type("custBank")
    @guaranteetype = get_dict_by_type("guaranteeType")
    @custrequesttype = get_dict_by_type("requestType")    
    @custtype = get_dict_by_type("custType")
  end
  
  def create
    if user_type(current_user) == 2
      redirect_to root_path, :flash => { :error => "您无权建立贷款流程"}
    else
      @custloan = Custloan.new(params[:custloan])
      if @custloan.save
        # redirect_to @custloan, :flash => { :success => "信贷流程建立"}
        # redirect_to loan_steps_path
        redirect_to custloan_loan_step_path(@custloan, :two)
      else  
        @title = "1 初步可行性"
        render 'new'
      end
    end
  end

  def edit
    @custloan  = Custloan.find(params[:id])
    @title = "修改信贷流程"
  end
  
  def update
    @custloan  = Custloan.find(params[:id])
    if @custloan.update_attributes(params[:custloan])
      redirect_to @custloan, :flash => { :success => "信贷流程更新成功" }
      # redirect_to loan_steps_path
    else  
      @title = "新建信贷流程"
      render 'edit'
    end 
  end

  def destroy
    @custloan.destroy
    redirect_to custloans_path, :flash => { :success => "信贷流程已撤销" }
  end
  
  def roll_back
    @custloan  = Custloan.find(params[:id])
    @notice = Notice.find_by_custloan_id(params[:id])
    @custloan.update_attribute :status, get_dict("loanStatus", 1).id
    @notice.destroy
    redirect_to root_path
  end
  
  def loan_add
    @custloan  = Custloan.find(params[:id])
    # @custloan.update_attribute :status, get_dict("loanStatus", 1).id
    # @notice.destroy
    # redirect_to root_path
  end
  
  def paymentplan
    @title = "还款计划表"
    @custloan  = Custloan.find(params[:id])
    @cust = @custloan.cust
    @custloan.loanpaymentplans.build unless !@custloan.loanpaymentplans.blank?
  end
  
  private

    def nextstep
      @custloan = Cusnloan.find(params[:id])
    end
    
end

app/helpers/custloans_helper.rb
module CustloansHelper
  def cust_loan(id)
    @cust_loan = Custloan.find_by_id(id)
  end
end

app/views/custloans/_custloan.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>申请进度</th>
			<th>当前状态</th>
			<th>确认金额</th>
      <th>起始日期</th>
			<th>还款日期</th>
			<th></th>
    </tr>
  </thead>
  <tbody>
		<tr>
			<td><%= @cust_loan.current_step %></td>
			<td><%= get_dict_by_id(@cust_loan.status).name %></td>
			<td><%= @cust_loan.loanstepfifths.first.submit_amont if !@cust_loan.loanstepfifths.first.nil? %> 万</td>
			<td><%= @cust_loan.loanstepfours.first.request_date.to_s.to_date if !@cust_loan.loanstepfours.first.nil? %></td>
			<td><%= @cust_loan.end_date.to_s.to_date %></td>
			<td>
				<% if @cust_loan.user == current_user && get_dict_by_id(@cust_loan.status).code == 3 %>
					<p class="text-center"><%= link_to '新放款记录', custloan_loan_step_path(@cust_loan, :nine), :class => 'btn btn-small btn-danger' %></p>
				<% end %>
			</td>
		</tr>
		<tr>
			<td colspan="6">
				<p class="text-center">
					<%= link_to '详细信息', custloan_path(@cust_loan), :class => 'btn btn-primary' %>
					<% if get_dict_by_id(@cust_loan.status).code != 1 %>
					<%= link_to '还款计划', paymentplan_custloan_path(@cust_loan), :class => 'btn' %>
					<% end %>
				</p>
			</td>
		</tr>
	</tbody>
</table>

app/views/custloans/_fields.html.erb
<%= f.input :cust_id, as: :hidden, :input_html => { value: @cust.id } %>
<%= f.input :current_step, as: :hidden, input_html: { value: 1 } %>
<%= f.input :status, as: :hidden, input_html: { value: get_dict('loanStatus', 1).id } %>
<%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>

<fieldset>
	<p class="lead"><legend><strong>基本信息</strong></legend></p>
	<%= f.simple_fields_for :loanstepones do |p| %>
	<%= p.input :cust_id, as: :hidden, :input_html => { value: @cust.id } %>
	<%= p.input :companyname, :input_html => { :class => "span4" }, :label => '公司名称' %>
	<%= p.input :companyaddress, :input_html => { :class => "span6" }, :label => '办公地址' %>
	<%= p.input :custname, :label => '客户姓名' %>
	<%= p.input :phone, :label => '联系电话' %>
	<%= p.input :request_amont, :label => '要求贷款金额（万元）' %>
	<%= p.input :request_interest, :label => '要求贷款利率（年）', :wrapper => :append do %>
		<%= p.input_field :request_interest %><span class="add-on">%</span>
	<% end %>
	<%= p.input :special_request, :input_html => { :class => "span4" }, :label => '有无特殊要求' %>
	<%= p.input :request_date, :as => :date_picker, :label => '要求放款时间' %>
	<%= p.input :current_loan_status, :as => :text, :label => '当前负债情况',
	 						:input_html => { :class => "input-xlarge", :rows => '6' } %>
</fieldset>

<fieldset>
	<p class="lead"><legend><strong>抵押物信息</strong></legend></p>
	<br/>
	<%= f.simple_fields_for :loansteponeguarantees do |builder| %>
    <%= render 'loansteponeguarantee_fields', f: builder %>
  <% end %>
		<%= link_to_add_fields "新增", f, :loansteponeguarantees %>
</fieldset>

<fieldset>
	<p class="lead"><legend><strong>财务状况</strong></legend></p>
	<%= p.input :stream_status, :as => :text, :label => '流水情况（个人）',
	 						:input_html => { :class => "input-xlarge", :rows => '6' } %>
	<%= p.input :stream_status_company, :as => :text, :label => '流水情况（公司）',
							:input_html => { :class => "input-xlarge", :rows => '6' } %>
	<%= p.input :stream_status_other, :as => :text, :label => '流水情况（其他）',
							:input_html => { :class => "input-xlarge", :rows => '6' } %>
	<%= p.input :cust_request_type, :label => '客户需求点' %>
	<%= p.input :custtype,:collection => @custtype, :label => '经营主体性质', :include_blank => false %>
	<%= p.input :invoice_status, :label => '开票状况', :input_html => { :class => "span5" } %>
	<%= p.input :tex_status, :label => '纳税状况', :input_html => { :class => "span5" } %>
</fieldset>

<fieldset>
	<p class="lead"><legend><strong>资产信息</strong></legend></p>
	<br/>
	<%= f.simple_fields_for :loansteponeassets do |builder| %>
    <%= render 'loansteponeasset_fields', f: builder %>
  <% end %>
	<!-- <div class="btn"> -->
		<%= link_to_add_fields "新增", f, :loansteponeassets %>
	<!-- </div> -->
</fieldset>
<% end %>

app/views/custloans/_loanpaymentplandetail_fields.html.erb
<fieldset>
	<%= f.input :cust_id, as: :hidden, :input_html => { value: @cust.id } %>
	<%= f.input :time_number, collection: 1..120, input_html: { :class => "input-mini" }, :label => '期数' %>
	<%= f.input :payment_date, input_html: { :class => "input-small" }, :label => '还款日期' %>
	<%= f.input :capital, :label => '本期本金（元）' %>
	<%= f.input :interest, :label => '本期利息（元）' %>
	<%= f.input :sub_total, :label => '合计金额（元）' %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "删除", '#', class: "remove_fields" %>
</fieldset>

app/views/custloans/_loansteponeguarantee_fields.html.erb
<fieldset>
	<%= f.input :cust_id, as: :hidden, :input_html => { value: @cust.id } %>
  <%= f.input :address, :label => '地址', :input_html => { :class => "input-xlarge" } %>
  <%= f.input :area, :label => '面积' %>
	<%= f.input :owner, :label => '产权证上所有者' %>
	<%= f.input :estate_type, :collection => get_dict_by_type("estateType"), :label => '类型', :include_blank => false %>
	<%= f.input :complete_year, :label => '竣工年限' %>
	<%= f.input :floor, :label => '层数' %>
	<%= f.input :describe, :as => :text, :label => '评估信息',
	 						:input_html => { :class => "input-xlarge", :rows => '6' } %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "删除", '#', class: "remove_fields" %>
</fieldset>

app/views/custloans/_tab_no.html.erb
<div class="well">
	<p class="text-center muted">该步骤尚未执行</p>
</div>

app/views/custloans/_tabloan1.html.erb
<div class="well">
	<!-- <ul class="inline">
		<li> -->
			<dl class="dl-horizontal">
				<p class="lead text-center"><legend><strong>基本资料</strong></legend></p>
			<% if !@custloan.loanstepones.first.companyname.empty? %>
			  <dt>公司名称:</dt>
			  <dd><%= @custloan.loanstepones.first.companyname %></dd>
			<% end %>
			<% if !@custloan.loanstepones.first.companyaddress.empty? %>
				<dt>办公地址:</dt>
			  <dd><%= @custloan.loanstepones.first.companyaddress %></dd>
			<% end %>
			<% if !@custloan.loanstepones.first.custname.empty? %>
				<dt>客户姓名:</dt>
			  <dd><%= @custloan.loanstepones.first.custname %></dd>
			<% end %>
			<% if !@custloan.loanstepones.first.phone.empty? %>
				<dt>联系电话:</dt>
			  <dd><%= @custloan.loanstepones.first.phone %></dd>
			<% end %>
			<% if !@custloan.loanstepones.first.request_amont.nil? %>
				<dt>要求贷款金额（万元）:</dt>
			  <dd><%= @custloan.loanstepones.first.request_amont %></dd>
			<% end %>
			<% if !@custloan.loanstepones.first.request_interest.nil? %>
				<dt>要求贷款利率（年）:</dt>
			  <dd><%= @custloan.loanstepones.first.request_interest %></dd>
			<% end %>
			<% if !@custloan.loanstepones.first.request_date.nil? %>
				<dt>要求放款时间:</dt>
			  <dd><%= @custloan.loanstepones.first.request_date %></dd>
			<% end %>
			<% if !@custloan.loanstepones.first.special_request.nil? %>
				<dt>有无特殊要求:</dt>
			  <dd><%= @custloan.loanstepones.first.special_request %></dd>
			<% end %>
			<% if !@custloan.loanstepones.first.current_loan_status.nil? %>
				<dt>当前负债情况:</dt>
			  <dd><%= @custloan.loanstepones.first.current_loan_status %></dd>
			<% end %>
			<br/>
				<p class="lead text-center"><legend><strong>抵押物信息</strong></legend></p>
				<% @custloan.loansteponeguarantees.each_with_index do |g,index| %>
				#<%= index + 1 %>
					<fieldset>
					<% if !g.address.nil? %>
						<dt>地址:</dt>
					  <dd><%= g.address %></dd>
					<% end %>
					<% if !g.area.nil? %>
						<dt>面积:</dt>
					  <dd><%= g.area %></dd>
					<% end %>
					<% if !g.owner.nil? %>
						<dt>产权证上所有者:</dt>
					  <dd><%= g.owner %></dd>
					<% end %>
					<% if !g.estate_type.nil? %>
						<dt>类型:</dt>
					  <dd><%= get_dict_by_id(g.estate_type).name unless g.estate_type.nil? %></dd>
					<% end %>
					<% if !g.complete_year.nil? %>
						<dt>竣工年限:</dt>
					  <dd><%= g.complete_year %></dd>
					<% end %>
					<% if !g.floor.nil? %>
						<dt>层数:</dt>
					  <dd><%= g.floor %></dd>
					<% end %>
					<% if !g.describe.nil? %>
						<dt>评估信息:</dt>
					  <dd><%= g.describe %></dd>
					<% end %>
					</fieldset>
				<% end %>
			<br/>
				<p class="lead text-center"><legend><strong>财务状况</strong></legend></p>
			<% if !@custloan.loanstepones.first.stream_status.empty? %>
				<dt>流水情况（个人）:</dt>
			  <dd><%= @custloan.loanstepones.first.stream_status %></dd>
			<% end %>
			<% if !@custloan.loanstepones.first.stream_status_company.empty? %>
				<dt>流水情况（公司）:</dt>
			  <dd><%= @custloan.loanstepones.first.stream_status_company %></dd>
			<% end %>
			<% if !@custloan.loanstepones.first.stream_status_other.empty? %>
				<dt>流水情况（其他）:</dt>
			  <dd><%= @custloan.loanstepones.first.stream_status_other %></dd>
			<% end %>
			<% if !@custloan.loanstepones.first.cust_request_type.empty? %>
				<dt>客户需求点:</dt>
			  <dd><%= @custloan.loanstepones.first.cust_request_type %></dd>
			<% end %>
			<% if !@custloan.loanstepones.first.custtype.nil? %>
				<dt>经营主体性质:</dt>
			  <dd><%= get_dict_by_id(@custloan.loanstepones.first.custtype).name unless @custloan.loanstepones.first.custtype.nil? %></dd>
			<% end %>
			<% if !@custloan.loanstepones.first.invoice_status.nil? %>
				<dt>开票状况:</dt>
			  <dd><%= @custloan.loanstepones.first.invoice_status %></dd>
			<% end %>
			<% if !@custloan.loanstepones.first.tex_status.nil? %>
				<dt>纳税状况:</dt>
			  <dd><%= @custloan.loanstepones.first.tex_status %></dd>
			<% end %>
			
			<br/>
				<p class="lead text-center"><legend><strong>资产信息</strong></legend></p>
				<% @custloan.loansteponeassets.each_with_index do |g,index| %>
				#<%= index + 1 %>
				<fieldset>
					<% if !g.asset_type.nil? %>
						<dt>类型:</dt>
					  <dd><%= get_dict_by_id(g.asset_type).name %></dd>
					<% end %>
						<dt>描述:</dt>
					<% if !g.describe.nil? %>
					  <dd><%= g.describe %></dd>
					<% end %>
				</fieldset>
				<% end %>
			</dl>
</div>

app/views/custloans/_tabloan10.html.erb
<div class="well">
	<dl class="dl-horizontal">
		<p class="lead text-center"><legend><strong>贷后客户交接</strong></legend></p>
		<% if !@custloan.loansteptens.first.user_id.blank? %>
		  <dt>贷后人员:</dt>
		  <dd><%= User.find(@custloan.loansteptens.first.user_id).name %></dd>
		<% end %>
	</dl>
</div>

app/views/custloans/_tabloan3.html.erb
<div class="well">
	<dl class="dl-horizontal">
		<p class="lead text-center"><legend><strong>现场尽职调查</strong></legend></p>
		<% if !@custloan.loanstepthrees.first.visit_time.blank? %>
		  <dt>上门时间:</dt>
		  <dd><%= @custloan.loanstepthrees.first.visit_time.strftime("%Y-%m-%d %H:%M:%S") %></dd>
		<% end %>
		<% if !@custloan.loanstepthrees.first.visit_place.blank? %>
		  <dt>上门地点:</dt>
		  <dd><%= @custloan.loanstepthrees.first.visit_place %></dd>
		<% end %>
		<% if !@custloan.loanstepthrees.first.broker_id.blank? %>
		  <dt>客户经理:</dt>
		  <dd><%= User.find(@custloan.loanstepthrees.first.broker_id).name %></dd>
		<% end %>
		<% if !@custloan.loanstepthrees.first.company_id.blank? %>
		  <dt>客户经理:</dt>
		  <dd><%= User.find(@custloan.loanstepthrees.first.company_id).name %></dd>
		<% end %>
		<% if !@custloan.loanstepthrees.first.bank_emp.blank? %>
		  <dt>银行人员:</dt>
		  <dd><%= @custloan.loanstepthrees.first.bank_emp %></dd>
		<% end %>
		<% if !@custloan.loanstepthrees.first.end_time.blank? %>
		  <dt>结束时间:</dt>
		  <dd><%= @custloan.loanstepthrees.first.end_time.strftime("%Y-%m-%d %H:%M:%S") %></dd>
		<% end %>
		<% if !@custloan.loanstepthrees.first.subject.blank? %>
		  <dt>主要谈话内容:</dt>
		  <dd><%= @custloan.loanstepthrees.first.subject %></dd>
		<% end %>
	</dl>
</div>

app/views/custloans/index.html.erb
<div class="row-fluid">
	<div class="span12">
		<div class="well">
			<p class="lead text-center"><legend><strong>申报列表</strong></legend></p>
			<table class="table table-condensed table-striped table-bordered">
				<thead>
					<tr>
						<th><h5>客户姓名</h5></th>
						<th><h5>申请金额</h5></th>
						<th><h5>申请利率</h5></th>
						<th><h5>当前进度</h5></th>
						<th><h5>起始日期</h5></th>
						<th><h5>还款日期</h5></th>
					</tr>
				</thead>
			  <tbody>
				<% if !@custloans.nil? %>
					<% @custloans.each do |l| %>
						<tr>
							<td><%= link_to l.cust.fullname, custloan_path(l) %></td>
							<td><%= l.loanstepones.first.request_amont.to_s %>万</td>
							<td><%= l.loanstepones.first.request_interest %>%</td>
							<td><%= current_step(l.current_step) %></td>
							<td><%= l.loanstepfours.first.request_date.to_s.to_date if !l.loanstepfours.first.nil? %></td>
							<td><%= l.end_date.to_s.to_date %></td>
						</tr>
					<% end %>
				<% end %>
			  </tbody>
			</table>
			<% if User.manager?(current_user) %>
				<%= will_paginate @custloans, previous_label: h("<"), next_label: h(">") %>
			<% end %>
		</div>
	</div>
</div>

app/views/custloans/loan_add.html.erb
<div class="row-fluid">
	<div class="span9">
		<div class="well">
			<p class="lead text-center"><legend><strong>放款</strong></legend></p>
			<%= simple_form_for @custloan, :html => { :class => 'form-horizontal' } do |f| %>
				<%= render 'loan_add_fields', :f => f %>
				<div class="form-actions">
					<%= f.submit '完成', :class => 'btn btn-primary' %>
				</div>
			<% end %>
		</div>
	</div>
	<div class="span3">
		<%= render 'loan_steps/helps/nine_helps' %>
	</div>
</div>

app/views/custloans/new.html.erb
<div class="row-fluid">
	<div class="span9">
		<div class="well">
			<%= simple_form_for @custloan, :html => { :class => 'form-horizontal' } do |f| %>
				<%= render 'fields', :f => f %>
				<div class="form-actions">
					<%= f.submit "确认", :class => 'btn btn-primary' %>
					<%= link_to "取消", cust_path(@cust), :class => 'btn' %>
				</div>
			<% end %>
		</div>
	</div>
	<div class="span3">
		<%= render 'loan_steps/helps/one_helps' %>
	</div>
</div>