config/routes.rb
Cmwp::Application.routes.draw do
  resources :users do
    get 'user_cancel', :on => :member
  end
  resources :usrrels
  resources :notices
  resources :custs do
    resources :custloans
    resources :loanreports
  end
  resources :custloans do
    resources :loan_steps do
      get 'add_new', :on => :member
    end
    get 'roll_back', :on => :member
    get 'paymentplan', :on => :member
  end
  resources :loanreports do
    resources :loan_report_steps
    get 'loan_interest', :on => :member
  end
  resources :custrels
  resources :sessions, :only => [:new, :create, :destroy]
  resources :departments, :only => [:index, :show] do
    resources :deptindices do
      get 'dept_index', :on => :member
    end
  end
  resources :branches, :only => [:index, :show] do
    get 'typebrokers', :on => :member
    resources :branchindices do
      get 'branch_index', :on => :member
    end
  end
  resources :brokers, :only => [:index, :show] do
    resources :brokerindices do
      get 'broker_index', :on => :member
    end
    member do
      get :relbrokers
    end
  end
  resources :categories do
    get 'search', :on => :collection
  end
  
  root :to => 'pages#home'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new' 
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'  
  
  match '/todo',    :to => 'pages#todo'  
  
  

end

app/models/branch.rb
# == Schema Information
#
# Table name: branches
#
#  id            :integer(4)      not null, primary key
#  code          :string(255)
#  name          :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  department_id :integer(4)
#  supervisor    :string(255)
#  location      :string(255)
#  phone         :string(255)
#

class Branch < ActiveRecord::Base
  attr_accessible :code, :name
  belongs_to :department
  has_many :brokers
  has_many :branchindices
  
  default_scope   :order => 'branches.code' 
  
  # def typebrokers(broker_type)
  #   Broker.typebrokers(broker_type)
  # end
  # scope :type_brokers, lambda { |broker_type| type_broker(broker_type) }
  # 
  # private
  # 
  #   def self.type_broker(broker_type)
  #     following_ids = %(SELECT followed_id FROM relationships
  #                       WHERE follower_id = :user_id)
  #     where("user_id IN (#{following_ids}) OR user_id = :user_id",
  #           :user_id => user)
  #   end
end

app/controllers/branches_controller.rb
# encoding: utf-8
class BranchesController < ApplicationController
  before_filter :authenticate, :only => [:index, :show]
  
  def index
    @branches = Branch.all # .order("code").paginate(:page => params[:page]).per_page(20)
    @title    = "选择营业部"
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @branches }
    end
  end

  def show
    @branch     = Branch.find(params[:id])
    @title      = @branch.name
    @father_department = @branch.department
    @brokers    = @branch.brokers
    @broker_types = @brokers.select("broker_type").group("broker_type")
    
    if @branch.branchindices.order("month_id DESC").find_by_indextype(1005).nil?
      @broker_a_num = 0  
    else 
      @broker_a_num = @branch.branchindices.unscoped.order("month_id DESC").find_by_indextype(1005).occursum.round
    end
    if @branch.branchindices.order("month_id DESC").find_by_indextype(1006).nil?
      @broker_b_num = 0  
    else 
      @broker_b_num = @branch.branchindices.unscoped.order("month_id DESC").find_by_indextype(1006).occursum.round
    end
    if @branch.branchindices.order("month_id DESC").find_by_indextype(1007).nil?
       @broker_c_num = 0  
     else 
       @broker_c_num = @branch.branchindices.unscoped.order("month_id DESC").find_by_indextype(1007).occursum.round
     end
     if @branch.branchindices.order("month_id DESC").find_by_indextype(1008).nil?
       @broker_d_num = 0  
     else 
       @broker_d_num = @branch.branchindices.unscoped.order("month_id DESC").find_by_indextype(1008).occursum.round
     end
     @broker_num = @broker_a_num + @broker_b_num + @broker_c_num + @broker_d_num
     
     if @branch.branchindices.order("month_id DESC").find_by_indextype(1003).nil?
       @total_branch_cust = 0  
     else 
       @total_branch_cust = @branch.branchindices.unscoped.order("month_id DESC").find_by_indextype(1003).occursum.round
     end
    
    if @branch.branchindices.order("month_id DESC").find_by_indextype(1004).nil?
      @total_broker_cust = 0  
    else 
      @total_broker_cust = @branch.branchindices.unscoped.order("month_id DESC").find_by_indextype(1004).occursum.round
    end
    @total_cust = @total_broker_cust + @total_branch_cust
    
    if @branch.branchindices.order("month_id DESC").find_by_indextype(1012).nil?
      @total_avai_cust = 0  
    else 
      @total_avai_cust = @branch.branchindices.unscoped.order("month_id DESC").find_by_indextype(1012).occursum.round
    end
    if @branch.branchindices.order("month_id DESC").find_by_indextype(1013).nil?
      @total_broker_avai_cust = 0  
    else 
      @total_broker_avai_cust = @branch.branchindices.unscoped.order("month_id DESC").find_by_indextype(1013).occursum.round
    end
    
    if @branch.branchindices.order("month_id DESC").find_by_indextype(1001).nil?
      @total_commis = 0  
      @total_commis_last = 0
    else 
      @total_commis = @branch.branchindices.unscoped.order("month_id DESC").find_by_indextype(1001).occursum
      @total_commis_last = @branch.branchindices.unscoped.order("month_id   DESC").limit(1).offset(1).find_by_indextype(1001).occursum
    end
    if @branch.branchindices.order("month_id DESC").find_by_indextype(1002).nil?
       @total_broker_commis = 0  
    else 
       @total_broker_commis = @branch.branchindices.unscoped.order("month_id DESC").find_by_indextype(1002).occursum
    end
    if @total_commis_last == 0
     @increase_rate = 0
    else
     @increase_rate = ((@total_commis - @total_commis_last) / @total_commis_last)*100
    end    
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @branch }
    end
  end
  
  def typebrokers
    @branch = Branch.find(params[:id])
    @brokers    = @branch.brokers
    @broker_types = @brokers.select("broker_type").group("broker_type")
    @typebrokers = Broker.where("branch_id = ? AND broker_type = ? ", params[:id], params[:broker_type]).paginate(:page => params[:page]).per_page(10)
    @title  = "#{params[:broker_type]}"
    @father_department = @branch.department
  end
  # def typebrokers
  #   @branch       = Branch.find(params[:id])
  #   @brokers      = @branch.gettypebroker
  #   @type_brokers = @branch.typebrokers(params[:id])
  # end
  
end

app/helpers/branches_helper.rb
# encoding: utf-8
module BranchesHelper
  
  # def gettypebroker(broker_type)
  #   @branch = Branch.find(params[:id])
  #   @branch.brokers.typebrokers(broker_type)
  # end
  
end

app/views/branches/_branch.html.erb
<li><%= link_to branch.name, branch_path(branch) %></li>

app/views/branches/_branch_count.html.erb
<span><%= @branch_num %></span>

app/views/branches/_contentarea1.html.erb
<div class="hero-unit">
    <p><strong><%= @branch.name %></strong> 
			<% if !@branch.location.nil? %>
				位于 <%= @branch.location %> 
			<% end %>
			<% if !@branch.supervisor.nil? %>
				负责人 <%= @branch.supervisor %> 
			<% end %>
			<% if !@branch.phone.nil? %>
				联系电话 <%= @branch.phone %>
			<% end %>
		</p>
		<p>目前拥有在职营销团队成员 <%= @broker_num %> 名，
			其中全日制营销团队成员 <%= @broker_c_num %> 名，
			证券经纪人 <%= @broker_a_num %> 名 ，
			前台人员 <%= @broker_d_num %> 名
		</p>
		<p>客户数 <%= @total_cust %> 名， 
			 有效户 <%= @total_avai_cust %> 位；
			 营销团队客户数 <%= @total_broker_cust %> 名， 
			 有效户占 <%= @total_broker_avai_cust %> 位
		</p>
		<p>本月实现营业收入(净佣金) <%= (@total_commis / 10000).round(2) %> 万元， 
			 较上月增长 <%= @increase_rate.round(2) %> %；
			 其中，营销团队实现收入 <%= (@total_broker_commis / 10000).round(2) %> 万元
		</p>
</div>

app/views/branches/_showchart1.html.erb
<div class="well">
	<script type="text/javascript" charset="utf-8">
		$(function() {
			var _branch,_url,_url2
			_branch = <%= @branch.id %>
			_url = '/branches/' + _branch + '/branchindices/1001/branch_index.json'
			_url2 = '/branches/' + _branch + '/branchindices/1002/branch_index.json'

		  return $.get(_url, function(data_1) {
				return $.get(_url2, function(data_2) {
					var chart, _month
					    _month = [];
							data_1.map(function(y) {
															_month.push(y.month);
									          })

					new Highcharts.Chart({
						chart: {
							renderTo: "chart_1",
							type: 'area'
						},
						title: {
							text: "营业部收入情况"
						},
						xAxis: {
							categories: _month,
							tickInterval: 3
						},
						yAxis: {
							title: {
								text: "单位：亿"
							},
							min: 0,
							labels: {
										formatter: function() {
										   return this.value / 100000000;
										}
									}
						},
						credits: {
							enabled: false
						},
						series: [
						{
						name: '总净佣金',
						data: 	
							(function() {
						                var _results;
						                _results = [];
						                data_1.map(function(y) {
																						_results.push(y.total);
																          })
						                return _results;
						              })(),
							
						},
						{
						name: '营销团队净佣金',
						data: 	
							(function() {
						                var _results;
						                _results = [];
						                data_2.map(function(y) {
																						_results.push(y.total);
																          })
						                return _results;
						              })(),
					
						}
						]
					})
		   });
		  });
		 });
	</script>
	<div id="chart_1">
	</div>
</div>

app/views/branches/_showchart2.html.erb
<div class="well">
	<script type="text/javascript" charset="utf-8">
		$(function() {
			var _branch,_url,_url2
			_branch = <%= @branch.id %>
			_url = '/branches/' + _branch + '/branchindices/1003/branch_index.json'
			_url2 = '/branches/' + _branch + '/branchindices/1004/branch_index.json'

		  return $.get(_url, function(data_1) {
				return $.get(_url2, function(data_2) {
					var chart, _month
					    _month = [];
							data_1.map(function(y) {
															_month.push(y.month);
									          })

					new Highcharts.Chart({
						colors: ['#AA4643','#4572A7'],
						chart: {
							renderTo: "chart_2",
							type: 'column'
						},
						title: {
							text: "客户发展情况"
						},
						xAxis: {
							categories: _month,
							tickInterval: 3
						},
						yAxis: {
							title: {
								text: "单位：万"
							},
							min: 0,
							labels: {
											formatter: function() {
											   return this.value / 10000;
											}
										}
							},
              stackLabels: {
                  enabled: true,
                  style: {
                      fontWeight: 'bold',
                      color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                  }
							},
            tooltip: {
                formatter: function() {
                    return '<b>'+ this.x +'</b><br/>'+
                        this.series.name +': '+ this.y +'<br/>'+
                        '客户总数: '+ this.point.stackTotal;
                }
            },
            plotOptions: {
                column: {
                    stacking: 'normal',
                    dataLabels: {
                        enabled: false,
                        color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'
                    }
                }
            },
						credits: {
							enabled: false
						},
						series: [
						{
						name: '营销团队客户数',
						data: 	
							(function() {
						                var _results;
						                _results = [];
						                data_2.map(function(y) {
																						_results.push(y.total);
																          })
						                return _results;
						              })(),
							
						},
						{
						name: '营业部自主开发客户数',
						data: 	
							(function() {
						                var _results;
						                _results = [];
						                data_1.map(function(y) {
																						_results.push(y.total);
																          })
						                return _results;
						              })(),
					
						}
						]
					})
		   });
		  });
		 });
	</script>
	<div id="chart_2">
	</div>
</div>

app/views/branches/_showchart3.html.erb
<div class="well">
	<script type="text/javascript" charset="utf-8">
		$(function() {
			var _branch,_url,_url2
			_branch = <%= @branch.id %>
			_url = '/branches/' + _branch + '/branchindices/1005/branch_index.json'
			_url2 = '/branches/' + _branch + '/branchindices/1006/branch_index.json'
			_url3 = '/branches/' + _branch + '/branchindices/1007/branch_index.json'
			_url4 = '/branches/' + _branch + '/branchindices/1008/branch_index.json'

		  return $.get(_url, function(data_1) {
				return $.get(_url2, function(data_2) {
					return $.get(_url3, function(data_3) {
						return $.get(_url4, function(data_4) {
						var chart, _month
						var i=-1, j=-1, n=-1, m=-1;
						for (x in data_1) {
						    if (data_1.hasOwnProperty(x)) ++i;
						}
						for (x in data_2) {
						    if (data_2.hasOwnProperty(x)) ++j;
						}
						for (x in data_3) {
						    if (data_3.hasOwnProperty(x)) ++n;
						}
						for (x in data_4) {
						    if (data_4.hasOwnProperty(x)) ++m;
						}
						// alert (this.point)
						new Highcharts.Chart({
							// colors: ['#AA4643','#4572A7'],
							chart: {
								renderTo: "chart_3",
								plotBackgroundColor: null,
								plotBorderWidth: null,
                plotShadow: false
							},
							title: {
								text: "营销团队发展情况"
							},
	            tooltip: {
	              formatter: function() {
							  	return '<b>'+ this.point.name +'</b>: '+ this.y + '名';
								}
	            },
	            plotOptions: {
	                pie: {
	                    allowPointSelect: true,
	                    cursor: 'pointer',
	                    dataLabels: {
	                        enabled: true,
	                        color: '#000000',
	                        connectorColor: '#000000',
	                        formatter: function() {
	                            return '<b>'+ this.point.name +'</b>: '+ this.percentage.toFixed(0) +' %';
	                        }
	                    }
	                }
	            },
							credits: {
								enabled: false
							},
							series: [{
								type: 'pie',
								data: [
									{ name: '证券经纪人', y: data_1[i].total },
		          		{ name: '非全日制营销人员', y: data_2[j].total },
				          { name: '全日制营销人员', y: data_3[n].total },
									{ name: '前台人员', y: data_4[m].total },
		            ]
							}]
						})
					});
			   });
			  });
		  });
		 });
	</script>
	<div id="chart_3">
	</div>
</div>

app/views/branches/_showchart4.html.erb
<div class="well">
	<script type="text/javascript" charset="utf-8">
		$(function() {
			var _branch,_url,_url2
			_branch = <%= @branch.id %>
			_url = '/branches/' + _branch + '/branchindices/1009/branch_index.json'
			_url2 = '/branches/' + _branch + '/branchindices/1010/branch_index.json'
			_url3 = '/branches/' + _branch + '/branchindices/1011/branch_index.json'

		  return $.get(_url, function(data_1) {
				return $.get(_url2, function(data_2) {
					return $.get(_url3, function(data_3) {
					var chart, _month
					    _month = [];
							data_1.map(function(y) {
															_month.push(y.month);
									          })

					new Highcharts.Chart({
						colors: ['#89a54e','#AA4643','#4572A7'],
						chart: {
							renderTo: "chart_4",
							type: 'bar'
						},
						title: {
							text: "营销团队支出情况"
						},
						xAxis: {
							categories: _month,
							// tickInterval: 3
						},
						yAxis: {
							title: {
								text: "单位：万"
							},
							min: 0,
							labels: {
										formatter: function() {
										   return this.value / 10000;
										}
									}
						},
						credits: {
							enabled: false
						},
						plotOptions: {
									series: {
										stacking: 'normal'
									}
								},
				    tooltip: {
                formatter: function() {
                    return '<b>'+ this.x +'</b><br/>'+
                        this.series.name +': '+ this.y +'<br/>'+
                        '总报酬支出:'+ this.point.stackTotal;
                }
            },
						series: [
						{
						name: '融资融券报酬',
						data: 	
							(function() {
						                var _results;
						                _results = [];
						                data_2.map(function(y) {
																						_results.push(y.total);
																          })
						                return _results;
						              })(),
					
						},
						{
						name: '报价回购报酬',
						data: 	
							(function() {
						                var _results;
						                _results = [];
						                data_3.map(function(y) {
																						_results.push(y.total);
																          })
						                return _results;
						              })(),
					
						},
						{
						name: '普通交易报酬',
						data: 	
							(function() {
						                var _results;
						                _results = [];
						                data_1.map(function(y) {
																						_results.push(y.total);
																          })
						                return _results;
						              })(),
							
						}
						]
					})
				});
		   });
		  });
		 });
	</script>
	<div id="chart_4">
	</div>
</div>

app/views/branches/_sidebar_brokertype.html.erb
<div class="span2">
	<div class="sidebar-nav">
		<ul class="nav nav-list well">
		  <li class="nav-header"><%= @branch.name %></li>
			<% @broker_types.each do |name| %>
				<li><%= link_to name.broker_type, typebrokers_branch_path(:broker_type => name.broker_type) %>
			<% end %>
		  <li class="divider"></li>
		</ul>
	</div>
</div>

app/views/branches/index.html.erb
<%= render "branches/sidebar_brokertype" %>

app/views/branches/show.html.erb
<%= render "branches/sidebar_brokertype" %>
	
<div class="span10">
	<div class="row-fluid">
		<div class="span12">
			<%= render 'branches/contentarea1' %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
	  	<%= render 'branches/showchart1' %>
		</div>
		<div class="span6">
			<%= render 'branches/showchart2' %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<%= render 'branches/showchart3' %>
		</div>
		<div class="span6">
			<%= render 'branches/showchart4' %>
		</div>	
	</div>
</div>

app/views/branches/typebrokers.html.erb
<%= render "branches/sidebar_brokertype" %>
<div class="span10">
	<%= render @typebrokers %>
	<%= will_paginate @typebrokers, previous_label: h("<"), next_label: h(">") %>
	</table>
</div>