config/routes.rb
Cmwp::Application.routes.draw do
  resources :users do
    get 'user_cancel', :on => :member
  end
  resources :usrrels
  resources :notices
  resources :custs do
    resources :custloans
    resources :loanreports
  end
  resources :custloans do
    resources :loan_steps do
      get 'add_new', :on => :member
    end
    get 'roll_back', :on => :member
    get 'paymentplan', :on => :member
  end
  resources :loanreports do
    resources :loan_report_steps
    get 'loan_interest', :on => :member
  end
  resources :custrels
  resources :sessions, :only => [:new, :create, :destroy]
  resources :departments, :only => [:index, :show] do
    resources :deptindices do
      get 'dept_index', :on => :member
    end
  end
  resources :branches, :only => [:index, :show] do
    get 'typebrokers', :on => :member
    resources :branchindices do
      get 'branch_index', :on => :member
    end
  end
  resources :brokers, :only => [:index, :show] do
    resources :brokerindices do
      get 'broker_index', :on => :member
    end
    member do
      get :relbrokers
    end
  end
  resources :categories do
    get 'search', :on => :collection
  end
  
  root :to => 'pages#home'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new' 
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'  
  
  match '/todo',    :to => 'pages#todo'  
  
  

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  attr_accessible :assist_user_id, :cust_id, :note, :status, :user_id, :vaild_date, :custloan_id,
                  :note_type, :loaninterestplan_id
  
  belongs_to :user
end
# == Schema Information
#
# Table name: notices
#
#  id                  :integer         not null, primary key
#  user_id             :integer
#  cust_id             :integer
#  assist_user_id      :integer
#  status              :integer
#  vaild_date          :datetime
#  note                :string(255)
#  created_at          :datetime        not null
#  updated_at          :datetime        not null
#  custloan_id         :integer
#  note_type           :integer
#  loaninterestplan_id :integer
#

app/controllers/notices_controller.rb
# encoding: utf-8
class NoticesController < ApplicationController
  before_filter :authenticate, :only => [:index, :show, :edit, :update, :destroy]
  
  def index
    @notices = Notice.find_by_assist_user_id(current_user.id).order("updated_at").paginate(
                :page => params[:page]).per_page(10)
    @title = "通知"
    
    respond_to do |format|
      format.html
      format.json { render json: @notices }
    end
  end
  
  def show
    @notice = Notice.find(params[:id])
    @title = "通知"
  end
  
  def update
    @notice = Notice.find(params[:id])
    if @notice.update_attributes(params[:notice])
      redirect_to root_path
    end
  end
end

app/helpers/notices_helper.rb
# encoding: utf-8
module NoticesHelper
  def get_note(user)
    custs = current_user.custs.find_birthdays_for(Time.now, -7.days.ago)
    custs.each do |c|
      @notice = Notice.find_by_cust_id_and_note_type( c.id, get_dict('noteType', 3).id )
      if @notice.nil? || (c.birthday - @notice.vaild_date.to_date).to_i > 7
        Notice.create( { :user_id => user.id, 
                         :assist_user_id => user.id,
                         :cust_id => c.id,
                         :vaild_date => Time.now,
                         :status => get_dict('noteStatus', 1).id,
                         :note_type => get_dict('noteType', 3).id,
                         :note => "客户#{c.fullname}生日提醒" } )
      end
    end
    custs = current_user.custs.find_partner_birthdays_for(Time.now, -7.days.ago)
    custs.each do |c|
      @notice = Notice.find_by_cust_id_and_note_type( c.id, get_dict('noteType', 5).id )
      if @notice.nil? || (c.birthday - @notice.vaild_date.to_date).to_i > 7
        Notice.create( { :user_id => user.id, 
                         :assist_user_id => user.id,
                         :cust_id => c.id,
                         :vaild_date => Time.now,
                         :status => get_dict('noteStatus', 1).id,
                         :note_type => get_dict('noteType', 5).id,
                         :note => "客户#{c.fullname}配偶生日提醒" } )
      end
    end
    
    custs = current_user.custs
    custs.each do |c|
      Loaninterestplan.cust_plans(c).each do |p|
        if (p.plan_date - Time.now.to_date).to_i <= 7 && (p.plan_date - Time.now.to_date).to_i >= 0
          @notice = Notice.find_by_cust_id_and_note_type( c.id, get_dict('noteType', 4).id )
          if @notice.nil?
            Notice.create( { :user_id => user.id, 
                             :assist_user_id => user.id,
                             :cust_id => c.id,
                             :vaild_date => Time.now,
                             :status => get_dict('noteStatus', 1).id,
                             :note_type => get_dict('noteType', 4).id,
                             :loaninterestplan_id => p.id,
                             :note => "客户#{c.fullname}到期还息提醒" } )
          end         
        end
      end
    end
  end
end

app/views/notices/_notice.html.erb
<div>
	<div class="well well-small">
		<h3><p class="lead text-info text-center">通知列表</p></h3>
		<table class="table table-condensed table-striped table-bordered">
			<thead>
				<tr>
					<th>
						<h5>内容</h5>
					</th>
					<th>
						<h5>提交人</h5>
					</th>
					<th>
						<h5>客户</h5>
					</th>
					<th>
						<h5>提交时间</h5>
					</th>
					<th>
						<h5>通知类型</h5>
					</th>
					<th></th>
				</tr>
			</thead>
		  <tbody>
				<% @notices.each do |n| %>
					<% case n.note_type %>
					<% when get_dict('noteType', 1).id %>
					<tr>
						<td><%= n.note %></td>
						<td><%= User.find(n.user_id).name %></td>
						<td><%= link_to Cust.find(n.cust_id).fullname, custloan_path(n.custloan_id) %></td>	
						<td><%= I18n.localize(n.updated_at, :format => :short) %></td>
						<td><%= Dict.find(n.note_type).name %></td>
						<td>
							<a href="#myModal<%=n.id%>" role="button" class="btn btn-mini pull-right" data-toggle="modal">查看</a>
						</td>	
						<%= render 'notices/notice_modal_2', :n => n %>
					</tr>
					<% when get_dict('noteType', 3).id %>
					<tr>
						<td><%= n.note %></td>
						<td><%= User.find(n.user_id).name %></td>
						<td><%= link_to Cust.find(n.cust_id).fullname, cust_path(n.cust_id) %></td>	
						<td><%= I18n.localize(n.updated_at, :format => :short) %></td>
						<td><%= Dict.find(n.note_type).name %></td>
						<td>
							<a href="#myModal<%=n.id%>" role="button" class="btn btn-mini pull-right" data-toggle="modal">查看</a>
						</td>	
						<%= render 'notices/notice_modal_3', :n => n %>
					</tr>
					
					<% when get_dict('noteType', 5).id %>
					<tr>
						<td><%= n.note %></td>
						<td><%= User.find(n.user_id).name %></td>
						<td><%= link_to Cust.find(n.cust_id).fullname, cust_path(n.cust_id) %></td>	
						<td><%= I18n.localize(n.updated_at, :format => :short) %></td>
						<td><%= Dict.find(n.note_type).name %></td>
						<td>
							<a href="#myModal<%=n.id%>" role="button" class="btn btn-mini pull-right" data-toggle="modal">查看</a>
						</td>	
						<%= render 'notices/notice_modal_5', :n => n %>
					</tr>
					
					<% when get_dict('noteType', 4).id %>
					<tr>
						<td><%= n.note %></td>
						<td><%= User.find(n.user_id).name %></td>
						<td><%= link_to Cust.find(n.cust_id).fullname, cust_path(n.cust_id) %></td>	
						<td><%= I18n.localize(n.updated_at, :format => :short) %></td>
						<td><%= Dict.find(n.note_type).name %></td>
						<td>
							<a href="#myModal<%=n.id%>" role="button" class="btn btn-mini pull-right" data-toggle="modal">查看</a>
						</td>	
						<%= render 'notices/notice_modal_4', :n => n %>
					</tr>
					<% end %>
				<% end %>
		  </tbody>
		</table>
	</div>
</div>

app/views/notices/_notice_modal.html.erb
<!-- Modal -->
<div id="myModal<%=n.id%>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><%= n.note %></h3>
  </div>
  <div class="modal-body">
    <p>提交时间：   <%= n.updated_at.to_formatted_s(:db) %></p>
		<p>客户全称：   <%= Cust.find(n.cust_id).fullname %></p>
		<p>申请贷款金额： <%= Custloan.find(n.custloan_id).total_amount %></p>
		<p>提交人：  	 <%= User.find(n.user_id).name %></p>
  </div>
	<%= form_for(current_user.custrels.build(:cust_id => n.cust_id)) do |f| %>
	<div><%= f.hidden_field :cust_id %></div>
  <div class="modal-footer">
    <!-- <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button> -->
		<%= link_to "退回", roll_back_custloan_path(n.custloan_id), :class => 'btn btn-danger' %>
		<%= f.submit "确认接收", :class => 'btn btn-primary' %>
  </div>
	<% end %>
</div>

app/views/notices/_notice_modal_2.html.erb
<!-- Modal -->
<div id="myModal<%=n.id%>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><%= n.note %></h3>
  </div>
  <div class="modal-body">
    <p>提交时间：   <%= n.updated_at.to_formatted_s(:db) %></p>
		<p>客户全称：   <%= Cust.find(n.cust_id).fullname %></p>
		<p>申请贷款金额： <%= Custloan.find(n.custloan_id).total_amount %></p>
		<p>提交人：  	 <%= User.find(n.user_id).name %></p>
  </div>
	<%= form_for(current_user.custrels.build(:cust_id => n.cust_id)) do |f| %>
	<div><%= f.hidden_field :cust_id %></div>
  <div class="modal-footer">
    <!-- <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button> -->
		<%= link_to "退回", roll_back_custloan_path(n.custloan_id), :class => 'btn btn-danger' %>
		<%= f.submit "确认接收", :class => 'btn btn-primary' %>
  </div>
	<% end %>
</div>

app/views/notices/_notice_modal_3.html.erb
<!-- Modal -->
<div id="myModal<%=n.id%>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><%= n.note %></h3>
  </div>
  <div class="modal-body">
    <p>提醒时间：   <%= n.updated_at.to_formatted_s(:db) %></p>
		<p>客户全称：   <%= Cust.find(n.cust_id).fullname %></p>
		<p>内容： 		 客户将在 <strong><%= I18n.localize(Cust.find(n.cust_id).birthday, :format => :short) %></strong> 过生日</p>
		<p>提醒人：  	 <%= User.find(n.user_id).name %></p>
  </div>
	<%= form_for n do |f| %>
	<div><%= f.hidden_field :status, value: get_dict('noteStatus', 3).id %></div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
		<%= f.submit "隐藏", :class => 'btn btn-primary' %>
  </div>
	<% end %>
</div>

app/views/notices/_notice_modal_4.html.erb
<!-- Modal -->
<div id="myModal<%=n.id%>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><%= n.note %></h3>
  </div>
  <div class="modal-body">
    <p>提醒时间：   <%= n.updated_at.to_formatted_s(:db) %></p>
		<p>客户全称：   <%= Cust.find(n.cust_id).fullname %></p>
		<p>内容： 		 客户将于 <strong><%= I18n.localize(Loaninterestplan.find(n.loaninterestplan_id).plan_date, :format => :short) %></strong> 还息 <strong><%= Loaninterestplan.find(n.loaninterestplan_id).interest %></strong> 元</p>
		<p>提醒人：  	 <%= User.find(n.user_id).name %></p>
  </div>
	<%= form_for n do |f| %>
	<div><%= f.hidden_field :status, value: get_dict('noteStatus', 3).id %></div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
		<%= f.submit "隐藏", :class => 'btn btn-primary' %>
  </div>
	<% end %>
</div>

app/views/notices/_notice_modal_5.html.erb
<!-- Modal -->
<div id="myModal<%=n.id%>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><%= n.note %></h3>
  </div>
  <div class="modal-body">
    <p>提醒时间：   <%= n.updated_at.to_formatted_s(:db) %></p>
		<p>客户全称：   <%= Cust.find(n.cust_id).fullname %></p>
		<p>内容： 		 客户配偶将在 <strong><%= I18n.localize(Cust.find(n.cust_id).partner_birthday, :format => :short) %></strong> 过生日</p>
		<p>提醒人：  	 <%= User.find(n.user_id).name %></p>
  </div>
	<%= form_for n do |f| %>
	<div><%= f.hidden_field :status, value: get_dict('noteStatus', 3).id %></div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
		<%= f.submit "隐藏", :class => 'btn btn-primary' %>
  </div>
	<% end %>
</div>

app/views/notices/index.html.erb
<div>
	<div class="page-header">
		<h3>通知列表</h3>
	</div>

	<table class="table table-condensed table-striped">
		<thead>
			<tr>
				<th>
					<h5>客户姓名</h5>
				</th>
			</tr>
		</thead>
	  <tbody>
			<%= render @notices %>
	  </tbody>
	</table>
</div>

app/views/notices/show.html.erb
<div class="page-header">
	<h1><%= @notice.note %></h1>
</div>

<table class="table table-condensed table-striped table-bordered">
	<thead>
		<tr>
			<th>
				<h4>客户姓名</h4>
			</th>
			<th>
				<h4>联系电话</h4>
			</th>
			<th>
				<h4>公司名称</h4>
			</th>
			<th>
				<h4>办公地址</h4>
			</th>
			<th>
				<h4>公司性质</h4>
			</th>
			<th>
				<h4></h4>
			</th>
		</tr>
	</thead>
  <tbody>
		<p>
			<%= @notice.note %>
		</p>
  </tbody>
</table>



</div>