config/routes.rb
Cmwp::Application.routes.draw do
  resources :users do
    get 'user_cancel', :on => :member
  end
  resources :usrrels
  resources :notices
  resources :custs do
    resources :custloans
    resources :loanreports
  end
  resources :custloans do
    resources :loan_steps do
      get 'add_new', :on => :member
    end
    get 'roll_back', :on => :member
    get 'paymentplan', :on => :member
  end
  resources :loanreports do
    resources :loan_report_steps
    get 'loan_interest', :on => :member
  end
  resources :custrels
  resources :sessions, :only => [:new, :create, :destroy]
  resources :departments, :only => [:index, :show] do
    resources :deptindices do
      get 'dept_index', :on => :member
    end
  end
  resources :branches, :only => [:index, :show] do
    get 'typebrokers', :on => :member
    resources :branchindices do
      get 'branch_index', :on => :member
    end
  end
  resources :brokers, :only => [:index, :show] do
    resources :brokerindices do
      get 'broker_index', :on => :member
    end
    member do
      get :relbrokers
    end
  end
  resources :categories do
    get 'search', :on => :collection
  end
  
  root :to => 'pages#home'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new' 
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'  
  
  match '/todo',    :to => 'pages#todo'  
  
  

end

app/controllers/loan_report_steps_controller.rb
# encoding: utf-8
class LoanReportStepsController < ApplicationController
  include Wicked::Wizard
  steps :two, :three, :four
  
  def show
    @title = "贷后调查报告"
    @loanreport = Loanreport.find(params[:loanreport_id])
    @cust = Cust.find_by_id(@loanreport.cust_id)
    
    case step
    when :two
      @title = "贷后调查报告"
    when :three
      @title = "贷后调查报告"
      @loanreport.loanreportcustomers.build unless !@loanreport.loanreportcustomers.blank?
      @loanreport.loanreportbanks.build unless !@loanreport.loanreportbanks.blank?
    when :four
      @title = "贷后调查报告"
    end
    render_wizard
  end
  
  def update
    @loanreport = Loanreport.find(params[:loanreport_id])
    @loanreport.update_attributes(params[:loanreport])
    
    render_wizard @loanreport, :flash => { :success => "流程更新成功" }
  end
end


 

app/helpers/loan_report_steps_helper.rb
module LoanReportStepsHelper
end

app/views/loan_report_steps/_four_fields.html.erb
<%= f.input :cust_id, as: :hidden, :input_html => { value: @cust.id } %>
<%= f.input :current_step, as: :hidden, input_html: { value: 4 } %>
<%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>

<div class="row-fluid">
	<div class="span6">
		<%= f.input :bank_suggest, :as => :text, :label => '客户贷款完成后对银行的建议',
		 						:input_html => { :rows => '6' } %>
	</div>
	<div class="span6">
		<%= f.input :cust_suggest, :as => :text, :label => '客户对我公司贷后服务的建议',
		 						:input_html => { :rows => '6' } %>
	</div>
</div>

app/views/loan_report_steps/_loanreportbank_fields.html.erb
<fieldset>
	<div class="row-fluid">
		<div class="span6">
			<%= f.input :bank, :collection => get_dict_by_type("custBank"), :label => '借款银行', :include_blank => false %>
		</div>
		<div class="span6">
			<%= f.input :loan_amount, :label => '借款金额（万）', input_html: { :class => "input-small" } %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<%= f.input :trust_type, :collection => get_dict_by_type("reportcustType"), :label => '授信种类', :include_blank => false %>
		</div>
		<div class="span6">
			<%= f.input :guarantee_type, :collection => get_dict_by_type("guaranteeType"), :label => '担保方式', :include_blank => false %>
		</div>
	</div>
		  <%= f.hidden_field :_destroy %>
		  <%= link_to "删除", '#', class: "remove_fields" %>
</fieldset>

app/views/loan_report_steps/_loanreportcustomer_fields.html.erb
<fieldset>
	<div class="row-fluid">
		<div class="span12">
			<%= f.input :cust_type, :collection => get_dict_by_type("reportcustType"), :label => '客户类型', :include_blank => false %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<%= f.input :cust_region, :collection => get_dict_by_type("custRegion"), :label => '所在地域', :include_blank => false %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<%= f.input :company_name, :label => '公司名称' %>
		</div>
		<div class="span6">
			<%= f.input :boss, :label => '负责人' %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<%= f.input :contact, :label => '联系方式' %>
		</div>
		<div class="span6">
			<%= f.input :address, :label => '经营地址' %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<%= f.input :financial, :label => '财务负责人' %>
		</div>
	</div>
		  <%= f.hidden_field :_destroy %>
		  <%= link_to "删除", '#', class: "remove_fields" %>
</fieldset>

app/views/loan_report_steps/_three_fields.html.erb
<%= f.input :cust_id, as: :hidden, :input_html => { value: @cust.id } %>
<%= f.input :current_step, as: :hidden, input_html: { value: 3 } %>
<%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>

<fieldset>
	<p class="lead"><legend><strong>管理及经营</strong></legend></p>
		<div class="row-fluid">
			<div class="span6">
				<%= f.input :first_charge_man, :label => "实际控制人（1）" %>
			</div>
			<div class="span6">
				<%= f.input :first_charge_man_changed, as: :select, :label => "变化状况" %>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6">
				<%= f.input :second_charge_man, :label => "实际控制人（2）" %>
			</div>
			<div class="span6">
				<%= f.input :second_charge_man_changed, as: :select, :label => "变化状况" %>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6">
				<%= f.input :financial_charge_man, :label => "财务负责人" %>
			</div>
			<div class="span6">
				<%= f.input :financail_charge_man_changed, as: :select, :label => "变化状况" %>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12">
				<%= f.input :sales_team_number, :label => "销售团队规模" %>
			</div>
		</div>
</fieldset>
<fieldset>
	<p class="lead"><legend><strong>公司主要客户</strong></legend></p>
		<div class="row-fluid">
			<div class="span12">
				<%= f.input :clients_detail, :as => :text, :label => '本年度公司上下游客户变化情况',
				 						:input_html => { :class => "input-xlarge", :rows => '6' } %>
			</div>
		</div>
		<p class="text-center"><h4>客户列表</h4></p>
		<%= f.simple_fields_for :loanreportcustomers do |builder| %>
			<%= render 'loanreportcustomer_fields', f: builder %>
	  <% end %>
		<%= link_to_add_fields "新增", f, :loanreportcustomers %>
</fieldset>
<fieldset>
	<p class="lead"><legend><strong>公司财务状况</strong></legend></p>
	<p><strong>1） 资产负债结构</strong></p>
	<div class="row-fluid">
		<div class="span6">
			<%= f.input :estate_1, :label => '房产1' %>
		</div>
		<div class="span6">
			<%= f.input :estate_2, :label => '房产2' %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<%= f.input :automobile, :label => '汽车' %>
		</div>
		<div class="span6">
			<%= f.input :assets, :label => '存款或理财产品' %>
		</div>
	</div>
	<fieldset>
	<p><strong>负债情况</strong></p>
		<%= f.simple_fields_for :loanreportbanks do |builder| %>
			<%= render 'loanreportbank_fields', f: builder %>
	  <% end %>
		<%= link_to_add_fields "新增", f, :loanreportbanks %>
	</fieldset>
	<p><strong>2） 现金流状况</strong> （现金流周期：贷款之日起--至今）</p>
	<div class="row-fluid">
		<div class="span6">
			<%= f.input :loan_bank_cash_stream, :as => :text, :label => '存款银行现金流',
			 						:input_html => { :rows => '6' } %>
		</div>
		<div class="span6">
			<%= f.input :other_bank_cash_stream, :as => :text, :label => '非存款银行现金流',
			 						:input_html => { :rows => '6' } %>
		</div>
	</div>
	<p><strong>3） 盈利能力</strong></p>
	<div class="row-fluid">
		<div class="span4">
			<%= f.input :turnover_1, :label => '淡季营业额', :input_html => { :class => "input-small" } %>
		</div>
		<div class="span4">
			<%= f.input :turnover_2, :label => '旺季营业额', :input_html => { :class => "input-small" } %>
		</div>
		<div class="span4">
			<%= f.input :turnover_3, :label => '年度营业额', :input_html => { :class => "input-small" } %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span4">
			<%= f.input :gross_profit_1, :label => '淡季毛利润', :input_html => { :class => "input-small" } %>
		</div>
		<div class="span4">
			<%= f.input :gross_profit_2, :label => '旺季毛利润', :input_html => { :class => "input-small" } %>
		</div>
		<div class="span4">
			<%= f.input :gross_profit_3, :label => '年度毛利润', :input_html => { :class => "input-small" } %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span4">
			<%= f.input :cost_1, :label => '淡季费用', :input_html => { :class => "input-small" } %>
		</div>
		<div class="span4">
			<%= f.input :cost_2, :label => '旺季费用', :input_html => { :class => "input-small" } %>
		</div>
		<div class="span4">
			<%= f.input :cost_3, :label => '年度费用', :input_html => { :class => "input-small" } %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span4">
			<%= f.input :pure_profit_1, :label => '淡季净利润', :input_html => { :class => "input-small" } %>
		</div>
		<div class="span4">
			<%= f.input :pure_profit_2, :label => '旺季净利润', :input_html => { :class => "input-small" } %>
		</div>
		<div class="span4">
			<%= f.input :pure_profit_3, :label => '年度净利润', :input_html => { :class => "input-small" } %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<%= f.input :bussiness_period, :label => '行业淡旺季周期', :input_html => { :class => "input-xlarge" } %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<%= f.input :period_gap, :label => '淡旺季销售差距', :input_html => { :class => "input-xlarge" } %>
		</div>
	</div>
</fieldset>

app/views/loan_report_steps/_two_fields.html.erb
<%= f.input :cust_id, as: :hidden, :input_html => { value: @cust.id } %>
<%= f.input :current_step, as: :hidden, input_html: { value: 2 } %>
<%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>


<%= f.input :loan_amont, :label => "借款金额（万）" %>
<%= f.input :loan_type, :collection => get_dict_by_type("guaranteeType"), :label => "担保方式", :include_blank => false %>
<%= f.input :withdrawal_date, :as => :date_picker, :label => "借款提款日" %>
<%= f.input :credit_deadline, :label => "授信期限" %>
<%= f.input :guaranty_detail, :input_html => { :class => "span6" }, :label => "抵押物明细" %>
<%= f.input :interest_rate, :label => '利率（年）', :wrapper => :append do %>
	<%= f.input_field :interest_rate %><span class="add-on">%</span>
<% end %>
<%= f.input :guaranty_address, :input_html => { :class => "span6" }, :label => "抵押物地址" %>
<%= f.input :bank, :collection => get_dict_by_type("custBank"), :label => "借款银行", :include_blank => false %>
<%= f.input :evaluate_price, :label => "评估价（万）" %>
<%= f.input :bank_broker, :label => "银行客户经理" %>
<%= f.input :bank_broker_mobile, :label => "客户经理手机" %>
<fieldset>
	<p class="lead"><legend><strong>收费信息</strong></legend></p>
		<div class="row-fluid">
			<div class="span6">
				<%= f.input :first_year_charge_rate, :label => '首年收费比例', :wrapper => :append do %>
					<%= f.input_field :first_year_charge_rate %><span class="add-on">%</span>
				<% end %>
			</div>
			<div class="span6">
				<%= f.input :first_year_charge, :label => "实际收费金额(元)" %>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6">
				<%= f.input :second_year_charge_rate, :label => '次年收费比例', :wrapper => :append do %>
					<%= f.input_field :second_year_charge_rate %><span class="add-on">%</span>
				<% end %>
			</div>
			<div class="span6">
				<%= f.input :second_year_charge, :label => "实际收费金额(元)" %>
			</div>
		</div>
</fieldset>
<fieldset>
	<p class="lead"><legend><strong>首年成本支出</strong></legend></p>
		<div class="row-fluid">
			<div class="span6">
				<%= f.input :evaluate_fee, :label => "评估费（元）" %>
			</div>
			<div class="span6">
				<%= f.input :notarial_fee, :label => "公证费（元）" %>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6">
				<%= f.input :insurance, :label => "保险费（元）" %>
			</div>
			<div class="span6">
				<%= f.input :registration_fee, :label => "抵押登记费（元）" %>
			</div>
		</div>
</fieldset>

app/views/loan_report_steps/four.html.erb
<div class="row-fluid">
	<div class="span9">
		<div class="well">
			<p class="lead text-center"><legend><strong>贷后服务建议</strong></legend></p>
			<%= simple_form_for @loanreport,:url => wizard_path, :method => :put, :html => { :class => 'form-horizontal' } do |f| %>
				<%= render 'four_fields', :f => f %>
				<div class="form-actions">
					<%= link_to '上一步', previous_wizard_path, :class => 'btn' %>
					<%= f.submit "完成", :class => 'btn btn-primary' %>
				</div>
			<% end %>
		</div>
	</div>
	<div class="span3">
		<%= render 'loanreports/helps/four_helps' %>
	</div>
</div>

app/views/loan_report_steps/show.html.erb
123

app/views/loan_report_steps/three.html.erb
<div class="row-fluid">
	<div class="span9">
		<div class="well">
			<p class="lead text-center"><legend><strong>公司经营状况</strong></legend></p>
			<%= simple_form_for @loanreport,:url => wizard_path, :method => :put, :html => { :class => 'form-horizontal' } do |f| %>
				<%= render 'three_fields', :f => f %>
				<div class="form-actions">
					<%= link_to '上一步', previous_wizard_path, :class => 'btn' %>
					<%= f.submit "下一步", :class => 'btn btn-primary' %>
				</div>
			<% end %>
		</div>
	</div>
	<div class="span3">
		<%= render 'loanreports/helps/three_helps' %>
	</div>
</div>

app/views/loan_report_steps/two.html.erb
<div class="row-fluid">
	<div class="span9">
		<div class="well">
			<p class="lead text-center"><legend><strong>融资基本信息</strong></legend></p>
			<%= simple_form_for @loanreport,:url => wizard_path, :method => :put, :html => { :class => 'form-horizontal' } do |f| %>
				<%= render 'two_fields', :f => f %>
				<div class="form-actions">
					<%= link_to '上一步', edit_loanreport_path(@loanreport), :class => 'btn' %>
					<%= f.submit "下一步", :class => 'btn btn-primary' %>
				</div>
			<% end %>
		</div>
	</div>
	<div class="span3">
		<%= render 'loanreports/helps/two_helps' %>
	</div>
</div>